language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.3

matrix:
 exclude:
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=master
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=master

env:
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
#  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
